# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")

SOURCES += \
    $$PWD/diywidgit/htmlparser/Extensions.cc \
    $$PWD/diywidgit/htmlparser/Node.cc \
    $$PWD/diywidgit/htmlparser/ParserDom.cc \
    $$PWD/diywidgit/htmlparser/ParserSax.cc \
    $$PWD/diywidgit/htmlparser/Uri.cc \
    $$PWD/diywidgit/htmlparser/utils.cc



